### ISSUE TITLE
✨ [Feature] 사용자 정보 조회 API

### ISSUE THREAD

**Issue by ooheunda** [INgandle/matjum#10]
### Description

**`GET /api/members/:id`**
패스워드를 제외한 모든 사용자의 정보를 조회합니다.

### Todo

- [x] 비즈니스 로직 구현
- [x] 스웨거 적용
- 예외처리
  - [x] `404` 해당하는 사용자가 존재하지 않는 경우
  - [x] `401` 인증되지 않은 사용자의 접근인 경우 (글로벌 가드 사용)
