### ISSUE TITLE
✨ [Feature] 사용자 설정 업데이트 API

### ISSUE THREAD

**Issue by ooheunda** [INgandle/matjum#12]
### Description

**`PATCH api/memebers/:id/settings`**
- 사용자의 위치인 lat(위도), lon(경도)를 업데이트 합니다.
  사용자 브라우저(웹or앱)에서 위도, 경도 정보를 가지고 호출한다는 전제로 구현합니다.
- 추천 기능 사용 여부를 업데이트 합니다.

### Todo

- [x] 비즈니스 로직 구현
- [x] 스웨거 적용
- 예외처리
  - [x] `404` 해당하는 사용자가 존재하지 않는 경우
  - [x] `401` 인증되지 않은 사용자의 접근인 경우 (글로벌 가드 사용)
  - [x] `400` Request Body에서 받는 `lat`, `lon`, `isRecommendationEnabled` 타입이 올바르지 않은 경우 (class-validator 사용)

### ETC

**❓ 위도, 경도와 추천 기능 사용 여부가 구분되는데, 요구사항에선 해당 API에서 모두를 업데이트 할 수 있도록 요구하고 있어 어떻게 해야할지 헷갈립니다.**
*(28일 회의에서 논의한 내용)*
- 클라이언트에서 어떻게 호출하게 될 지가 문제일 것 같다.
  - 위, 경도 업데이트/사용 여부 업데이트 두 케이스로 나눠서 호출한다고 가정? (업데이트 안 되는 부분은 null)
  - 업데이트 안 되는 부분은 기존 정보를 넣어준다고 가정?
- 결론: 사용자 정보 조회 API 요구 사항에 관련된 내용이 있어 두 번째를 전제로.
