### ISSUE TITLE
🔨 [Chore] PostGIS 설정

### ISSUE THREAD

**Issue by kimdoyeonn** [INgandle/matjum#14]
### Description

PostgreSQL 데이터베이스의 확장 기능인 PostGIS 설정을 세팅합니다.
이 프로젝트에서는 두 지리적 좌표(사용자, 맛집) 사이의 거리를 계산하기 위해 사용됩니다.

### Todo

- [x] docker 이미지 변경
- [x] 자동으로 PostGIS를 활성화하기 위한 sql 추가
- [x] member 테이블에 location 컬럼 추가
- [x] restaurant 테이블에 location 컬럼 추가
