### ISSUE TITLE
✨ [Feature] 맛집 목록 API 구현

### ISSUE THREAD

**Issue by kimdoyeonn** [INgandle/matjum#6]
### Description

조건에 맞는 맛집 목록을 반환합니다.

- 필수: lon, lat, range
- 선택
  - sort-by: 거리순(기본), 별점순
  - pagination: page, page-size
  - search: 카테고리, 상호명을 기준으로 검색
  - filter(보류): 카테고리로 필터링

### 의문

- filter 기능을 구현 되면 search 기능이 필요할까?
  - 현재 검색에 사용할만한 데이터는 "상호명, 카테고리" 
  - filter 기능은 카테고리를 기준으로 필터링을 하게 될 것인데, 그럼 search 기능과 겹칠 것 같음

### Todo

- [x] 위치: lon, lat(사용자의 위도/경도), range(범위)
- [x] 정렬: sort-by(거리순, 별점순)
- [x] pagination: page, page-size
- [x] 검색: search
- [x] 필터링: filter - 보류
- [x] swagger 적용
- [x] 테스트코드 작성
